name:                rl-test
version:             0.1.0.0
github:              "jbrot/rl-test"
license:             BSD3
author:              "Joshua Brot"
maintainer:          "jbrot@umich.edu"
copyright:           "2019(c) Joshua Brot"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jbrot/rl-test#readme>

dependencies:
- base >= 4.7 && < 5
- mersenne-random-pure64
- random
- transformers

library:
  source-dirs: src

executables:
  rl-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl-test

tests:
  rl-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl-test
